from django.urls import re_path
from django.urls import path
from . import views
from taskapp.views import LoginView

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^dc_reg$', views.dc_reg, name='dc_reg'),
    re_path(r'^tl_reg$', views.tl_reg, name='tl_reg'),
    re_path(r'^exe_reg$', views.exe_reg, name='exe_reg'),
    # re_path(r'^login$',views.login,name='login'),
    path('login', LoginView.as_view()),
    re_path(r'^profile$', views.profile, name='profile'),
    re_path(r'^profile2$', views.profile2, name='profile2'),
    re_path(r'^tasks$', views.tasks, name='tasks'),
    re_path(r'^dctaskspage$', views.dctaskspage, name='dctaskspage'),
    re_path(r'^dctaskproduct$', views.dctaskproduct, name='dctaskproduct'),
    re_path(r'^dctasksoft$', views.dctasksoft, name='dctasksoft'),
    re_path(r'^dctaskrecruitment$', views.dctaskrecruitment, name='dctaskrecruitment'),
    re_path(r'^dcrecruitmenttask$', views.dcrecruitmenttask, name='dcrecruitmenttask'),
    re_path(r'^dcrecruitmentshare$', views.dcrecruitmentshare, name='dcrecruitmentshare'),
    re_path(r'^dctaskservices$', views.dctaskservices, name='dctaskservices'),
    re_path(r'^dcservicesshare$', views.dcservicesshare, name='dcservicesshare'),
    re_path(r'^tasks2$', views.tasks2, name='tasks2'),
    re_path(r'^taskstable/(?P<pk>\d+)/$', views.taskstable, name='taskstable'),
    re_path(r'^assign$', views.assign, name='assign'),
    # re_path('assign',ViewAssign.as_view()),
    re_path(r'^shared$', views.shared, name='shared'),
    re_path(r'^shared2$', views.shared2, name='shared2'),
    re_path(r'^shared3/(?P<pk>\d+)/$', views.shared3, name='shared3'),
    re_path(r'^shared4$', views.shared4, name='shared4'),
    # path('marktexe', Marktexe.as_view()),
    re_path(r'^marktexe$', views.marktexe, name='marktexe'),
    re_path(r'^marktexe2$', views.marktexe2, name='marktexe2'),
    re_path(r'^attendance$', views.attendance, name='attendance'),
    re_path(r'^attendance2$', views.attendance2, name='attendance2'),
    re_path(r'^reportissue$', views.reportissue, name='reportissue'),
    re_path(r'^reportissue2$', views.reportissue2, name='reportissue2'),
    re_path(r'^reportissue3$', views.reportissue3, name='reportissue3'),
    re_path(r'^reportissue4$', views.reportissue4, name='reportissue4'),
    re_path(r'^reportissue5$', views.reportissue5, name='reportissue5'),
    re_path(r'^payments$', views.payments, name='payments'),
    re_path(r'^payments2$', views.payments2, name='payments2'),
    re_path(r'^paymentstable$', views.paymentstable, name='paymentstable'),
    re_path(r'^applyleave$', views.applyleave, name='applyleave'),
    re_path(r'^applyleave2$', views.applyleave2, name='applyleave2'),
    re_path(r'^applyleave3$', views.applyleave3, name='applyleave3'),
    re_path(r'^applyleave4$', views.applyleave4, name='applyleave4'),

    # Team lead sectn

    # re_path(r'^tllogin$',views.tllogin,name='tllogin'),
    re_path(r'^tl1$', views.tl1, name='tl1'),
    re_path(r'^tl2$', views.tl2, name='tl2'),
    re_path(r'^tltask$', views.tltask, name='tltask'),
    re_path(r'^tltaskspage$', views.tltaskspage, name='tltaskspage'),
    re_path(r'^tltaskproduct$', views.tltaskproduct, name='tltaskproduct'),
    re_path(r'^tltaskrecruitment$', views.tltaskrecruitment, name='tltaskrecruitment'),
    re_path(r'^tltaskservice$', views.tltaskservice, name='tltaskservice'),
    re_path(r'^tltaskserviceshare$', views.tltaskserviceshare, name='tltaskserviceshare'),
    re_path(r'^tltaskservicedone$', views.tltaskservicedone, name='tltaskservicedone'),
    re_path(r'^tltask2$', views.tltask2, name='tltask2'),
    re_path(r'^tltasktable/(?P<pk>\d+)/$', views.tltasktable, name='tltasktable'),
    # re_path(r'^tltasktable/(?P<date>\d{4}-\d{2}-\d{2})/$', views.tltasktable, name='tltasktable'),
    re_path(r'^tlshared4$', views.tlshared4, name='tlshared4'),
    re_path(r'^tltask4$', views.tltask4, name='tltask4'),
    re_path(r'^tltask5$', views.tltask5, name='tltask5'),
    re_path(r'^tltask6$', views.tltask6, name='tltask6'),
    re_path(r'^tltask6shared$', views.tltask6shared, name='tltask6shared'),
    re_path(r'^tltask7/(?P<pk>\d+)/$', views.tltask7, name='tltask7'),
    re_path(r'^tltask7table/(?P<pk>\d+)/$', views.tltask7table, name='tltask7table'),
    re_path(r'^tlsaved$', views.tlsaved, name='tlsaved'),
    re_path(r'^tlshared$', views.tlshared, name='tlshared'),
    re_path(r'^tlsharedtable$', views.tlsharedtable, name='tlsharedtable'),
    re_path(r'^tlshared2$', views.tlshared2, name='tlshared2'),
    re_path(r'^tlshared3$', views.tlshared3, name='tlshared3'),
    re_path(r'^tldc$', views.tldc, name='tldc'),
    re_path(r'^tldc2$', views.tldc2, name='tldc2'),
    re_path(r'^tlattendance$', views.tlattendance, name='tlattendance'),
    re_path(r'^tlattendance2$', views.tlattendance2, name='tlattendance2'),
    re_path(r'^tlreport$', views.tlreport, name='tlreport'),
    re_path(r'^tlreport2$', views.tlreport2, name='tlreport2'),
    re_path(r'^tlreport3$', views.tlreport3, name='tlreport3'),
    re_path(r'^tlreport4$', views.tlreport4, name='tlreport4'),
    re_path(r'^tlreport5$', views.tlreport5, name='tlreport5'),
    re_path(r'^tlpayments$', views.tlpayments, name='tlpayments'),
    re_path(r'^tlpayments2$', views.tlpayments2, name='tlpayments2'),
    re_path(r'^tlpayments3$', views.tlpayments3, name='tlpayments3'),
    re_path(r'^tlapply$', views.tlapply, name='tlapply'),
    re_path(r'^tlapply1$', views.tlapply1, name='tlapply1'),
    re_path(r'^tlapply2$', views.tlapply2, name='tlapply2'),
    re_path(r'^tlapply3$', views.tlapply3, name='tlapply3'),

    # executive sectn

    # re_path(r'^exelogin$',views.exelogin,name='exelogin'),
    re_path(r'^exe1$', views.exe1, name='exe1'),
    re_path(r'^exe2$', views.exe2, name='exe2'),
    re_path(r'^exetask$', views.exetask, name='exetask'),
    re_path(r'^exetask2$', views.exetask2, name='exetask2'),
    re_path(r'^exetasktable/(?P<pk>\d+)/$', views.exetasktable, name='exetasktable'),
    re_path(r'^exetasktable2/(?P<pk>\d+)/$', views.exetasktable2, name='exetasktable2'),
    re_path(r'^exetableupdate22$', views.exetableupdate22, name='exetableupdate22'),
    re_path(r'^exetasktableupdate/(?P<pk>\d+)/$', views.exetasktableupdate, name='exetasktableupdate'),
    re_path(r'^exetableupdate1$', views.exetableupdate1, name='exetableupdate1'),
    re_path(r'^exetasktable3/(?P<pk>\d+)/$', views.exetasktable3, name='exetasktable3'),
    re_path(r'^exetasktable31/(?P<pk>\d+)/$', views.exetasktable31, name='exetasktable31'),
    re_path(r'^exetasktable3update$', views.exetasktable3update, name='exetasktable3update'),
    re_path(r'^exect$', views.exect, name='exect'),
    re_path(r'^execttable/(?P<pk>\d+)/$', views.execttable, name='execttable'),
    re_path(r'^exeattendance$', views.exeattendance, name='exeattendance'),
    re_path(r'^exeattendance2$', views.exeattendance2, name='exeattendance2'),
    re_path(r'^exereport$', views.exereport, name='exereport'),
    re_path(r'^exereport2$', views.exereport2, name='exereport2'),
    re_path(r'^exereport3$', views.exereport3, name='exereport3'),
    re_path(r'^exereport4$', views.exereport4, name='exereport4'),
    re_path(r'^exereport5$', views.exereport5, name='exereport5'),
    re_path(r'^exepayments$', views.exepayments, name='exepayments'),
    re_path(r'^exepayments2$', views.exepayments2, name='exepayments2'),
    re_path(r'^exepayments3$', views.exepayments3, name='exepayments3'),
    re_path(r'^exeapply$', views.exeapply, name='exeapply'),
    re_path(r'^exeapply1$', views.exeapply1, name='exeapply1'),
    re_path(r'^exeapply2$', views.exeapply2, name='exeapply2'),
    re_path(r'^exeapply3$', views.exeapply3, name='exeapply3'),

]